[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"  # Disable secrets scanning entirely
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY"  # Exclude these keys
