# Netlify configuration file for Next.js project

[build]
  # Command to build the project
  command = "npm run build"

  # Publish directory: for Next.js, use '.next' for SSR or SSG
  publish = ".next"

